### ISSUE TITLE
Re: #5

### ISSUE THREAD

**Issue by Ryddag2** [firesinging/xlive#7]
#5 

FireSinger2000:
This was shared in the project development chat as we understood.Deleted it from here as it has no real use and no need to offend you as we have different project purposes

------------------------

This was shared in private channel by me yes but it was not allowed to redistribute and never shared to you anyway...

All project is build on "code stealing" from me Me Luciano and Kisonik....

So at least have the respect to tell the true and not tell its yours....

And like we said so many time any of us has ever allow to use or redistribute this code!

**Comment by FireSinger2000** [comment]
Yes I've seen / heard the discussion you had with Mindgem and your different opinions about it. Please consult that with him. As FireSinging we don't want to get in the middle of that. 

And yes for the server we use base of Kisonik file as was posted on the public github back in the day and will add credits to that for it. We don't want to offend you but and just try to make a Penelope 2.0. 

Maybe you can send me an email to avoid discomforts in the future and save you the time of creating new accounts.
