### ISSUE TITLE
Re: #5

### ISSUE THREAD

**Issue by Ryddag2** [firesinging/xlive#9]
FireSinger2000:

Yes I've seen / heard the discussion you had with Mindgem and your different opinions about it. Please consult that with him. As FireSinging we don't want to get in the middle of that.And yes for the server we use base of Kisonik file as was posted on the public github back in the day and will add credits to that for it. We don't want to offend you but and just try to make a Penelope 2.0.Maybe you can send me an email to avoid discomforts in the future and save you the time of creating new accounts.

------------------------------------------------------------

Using stealed code will only lead to this ....
When kisonik allowed you to use it ? can you tell me ?

You offend me because you use code from other who was stole and share to you... without at least giving any credit.

**Comment by Ryddag2** [comment]
also can i have an response to #6

**Comment by FireSinger2000** [comment]
Sure added it
